Task 1
CVanta/Naumen-project pull request #3
Opened 2023-12-14 07:18 UTC by CVanta

2023-12-14 18:38 UTC, vpyzhyanov commented
### по Git:

Ветки не используете

![image](https://github.com/CVanta/Naumen-project/assets/71599019/2caf96c9-7c9c-4b64-8260-b55469cfb0a1)

Пулл реквесты тоже

![image](https://github.com/CVanta/Naumen-project/assets/71599019/35523478-073b-4378-8806-ee2dede8677a)

Итого: 1 балл и то только за комментарии к коммитам

2023-12-14 18:42 UTC, vpyzhyanov commented
Задача, которая не собирается и у которой не проходят тесты приниматься не будет!

![image](https://github.com/CVanta/Naumen-project/assets/71599019/f460533a-f9b4-4750-a307-e328f3c95d49)

![image](https://github.com/CVanta/Naumen-project/assets/71599019/979649d0-d2e5-4416-afd6-f4a281e9546e)


С какой стати спринговый контекст поднимается в тестах? Не должно его там и в помине быть

2023-12-14 19:59 UTC, vpyzhyanov requested changes
Задача без тестов не принимается!!!

Я одним небольшим изменением отрубил абсолютно весь функционал бота, но тесты успешно проходят.

![image](https://github.com/CVanta/Naumen-project/assets/71599019/5e077cac-e70c-4bb1-a4ff-6dfbf8a23929)

Следовательно тесты вообще ничего не гарантируют. Протестированы не все необходимые классы. Ни один сервис не протестирован.

2023-12-14 19:59 UTC, vpyzhyanov commented on .gitignore
`HELP.md` почему заигнорирван?

2023-12-14 19:59 UTC, vpyzhyanov commented on pom.xml
> +    </properties>
где кодировка?

2023-12-14 19:59 UTC, vpyzhyanov commented on pom.xml
> +                    <target>19</target>
Мы на какую версию Java договаривались? Почему у вас расхождение в настройках?

2023-12-14 19:59 UTC, vpyzhyanov commented on src/main/java/com/urfu/tgbot/configs/BotConfig.java
> +@Configuration
Неуместное использование этой аннотации. Этот класс конфигурацией не является. Почитайте зачем нужна эта аннотация.

Вкратце скажу, что конфигурация нужна для того. чтобы создавать бины. Вы же тут ни одного бина не создали.

2023-12-14 19:59 UTC, vpyzhyanov commented on src/main/java/com/urfu/tgbot/configs/BotConfig.java
> +    public void setBotToken(String botToken) {
это ещё зачем? Как может токен измениться во время работы приложения? Или это просто для того, что нарушить инкапсуляцию по полной, тогда public сделайте

2023-12-14 19:59 UTC, vpyzhyanov commented on src/main/java/com/urfu/tgbot/configs/BotConfig.java
> +    public void setBotName(String botName) {
это ещё зачем?

2023-12-14 19:59 UTC, vpyzhyanov commented on src/main/java/com/urfu/tgbot/configs/BotInitializer.java
> +            api.registerBot(bot);
Похоже ваш бот очень важный, раз он сам себя зарегистрировать не может и ему нужен слуга для этого.

В общем EventListener надо перенести в сам TelegramBot. Не надо тут ответственность размазывать, пусть бот сам за себя отвечает.

2023-12-14 19:59 UTC, vpyzhyanov commented on src/main/java/com/urfu/tgbot/configs/BotInitializer.java
> +
класс! Полное игнорирование. Не надо так. Лучше выкиньте тут исключение с человекочитаемым текстом

2023-12-14 19:59 UTC, vpyzhyanov commented on src/main/java/com/urfu/tgbot/enums/States.java
> +public enum States {
1. где JavaDoc?
2. Некорректно использовать множественное число в классах и пакетах. Я в прошлый раз это говорил.

2023-12-14 19:59 UTC, vpyzhyanov commented on src/main/java/com/urfu/tgbot/services/TelegramBot.java
> +package com.urfu.tgbot.services;
бот - это не сервис. Не надо никого путать. Вот я с трудом его нашёл, только по хлебным крошкам.

2023-12-14 19:59 UTC, vpyzhyanov commented on src/main/java/com/urfu/tgbot/services/TelegramBot.java
> +    public TelegramBot(BotConfig config, CommandManager commandManager) {
лучше писать Autiwired явно, чтобы всем было очевидно, где происходит инжект бинов. А то способы бывают разные

2023-12-14 19:59 UTC, vpyzhyanov commented on src/main/java/com/urfu/tgbot/services/TelegramBot.java
> +
не надо игнорировать ошибки. Хоть на экран их выведите что-ли, для порядку.

2023-12-14 19:59 UTC, vpyzhyanov commented on src/main/java/com/urfu/tgbot/commands/CommandManager.java
> +    public String readInput(String messageText, long chatId) {
имя метода и его описание противоречат друг другу. Имя метода тоже должно соответствовать тому, что метод реально делает, этот метод точно не читает никакие входные данные, они уже прочитанные пришли до него

2023-12-14 19:59 UTC, vpyzhyanov commented on src/main/java/com/urfu/tgbot/commands/CommandManager.java
> +@Controller
Если вы не понимаете зачем нужна аннотация, то не надо её писать

2023-12-14 19:59 UTC, vpyzhyanov commented on src/main/java/com/urfu/tgbot/commands/CommandManager.java
> +            case null -> {
Такая возможность выключена в Java 17. Да и вашем случае она не имеет никакого оправдания быть включенной, она неуместна. Для этого есть стандартная опция default

![image](https://github.com/CVanta/Naumen-project/assets/71599019/6a806b8f-1839-4e88-b275-91f2025c5007)

2023-12-14 19:59 UTC, vpyzhyanov commented on pom.xml
> +                    <compilerArgs>--enable-preview</compilerArgs>
уберите это

2023-12-14 19:59 UTC, vpyzhyanov commented on src/main/java/com/urfu/tgbot/commands/CommandManager.java
> +    public String readCommand(String command, long chatID) {
1. нарушение инкапсуляции. Это метод больше нигде не используется, только тут
2. Опять имя метода вводит в заблуждение. Никакие команды он не читает!

2023-12-14 19:59 UTC, vpyzhyanov commented on src/main/java/com/urfu/tgbot/commands/CommandManager.java
> +                return "Не удалось разпознать команду";
орфографическая ошибка

2023-12-14 19:59 UTC, vpyzhyanov commented on src/main/java/com/urfu/tgbot/commands/StartCommand.java
> +@Controller
Неуместное использование аннотации. Это ни разу не контроллер. Убирайте

2023-12-14 19:59 UTC, vpyzhyanov commented on src/main/java/com/urfu/tgbot/commands/EditCommand.java
> +    public void updateState(long chatID) {
добро пожаловать на тёмную сторону ООП. Функциональность по управлению состояниями размазана по целой куче классов.

2023-12-14 19:59 UTC, vpyzhyanov commented on src/main/java/com/urfu/tgbot/commands/NameEditor.java
> + * Этот класс реализует изменени профиля пользователя
дописывайте слова до конца

2023-12-14 19:59 UTC, vpyzhyanov commented on src/main/java/com/urfu/tgbot/commands/NameEditor.java
> +@Controller
это не контроллер

2023-12-14 19:59 UTC, vpyzhyanov commented on src/main/java/com/urfu/tgbot/commands/NameEditor.java
> +        } catch (Exception e) {
выглядит очень странно, вы вроде отлавливаете это исключение, но при этом говорите, что выкидываете его наружу, хотя сами это не делаете. Очень странно

2023-12-14 19:59 UTC, vpyzhyanov commented on src/main/java/com/urfu/tgbot/models/User.java
> +     * @return Отформатированная строковая representation информации о пользователе.
вот вам не лень 2 раза писать одно и то же

2023-12-14 19:59 UTC, vpyzhyanov commented on src/main/java/com/urfu/tgbot/models/User.java
> +    public long getPhoneNumber() {
Номер телефона это long? Серьёзно? Тогда имя пользователя по любому double должно быть)))

Номер телефона может быть только строкой!

2023-12-14 19:59 UTC, vpyzhyanov commented on src/main/java/com/urfu/tgbot/models/User.java
> +     * @return Полное имя пользователя.
Спасибо КЭП

2023-12-14 19:59 UTC, vpyzhyanov commented on src/main/java/com/urfu/tgbot/models/User.java
> +    public static class Builder {
1. static запрещён!
2. Неуместное использование билдера. Похоже вы хотели его применить для того, чтобы его применить. Поздравляю, применили, теперь убирайте. Вы абсолютно всегда заполняете **все** поля сразу, что полностью обесценивает билдер. Используйте конструктор.

2023-12-14 19:59 UTC, vpyzhyanov commented on src/main/java/com/urfu/tgbot/repositories/StatesRepository.java
> +public interface StatesRepository extends CrudRepository<State, Long> {
где JavaDoc?

2023-12-14 19:59 UTC, vpyzhyanov commented on src/main/java/com/urfu/tgbot/repositories/UserRepository.java
> +public interface UserRepository extends CrudRepository<User, Long> {
где JavaDoc?

2023-12-14 19:59 UTC, vpyzhyanov commented on src/main/java/com/urfu/tgbot/services/StateService.java
> +@Component
А это зачем?

2023-12-14 19:59 UTC, vpyzhyanov commented on src/main/java/com/urfu/tgbot/services/StateService.java
> +import java.util.List;
неиспользуемые импорты. Разве вы не видите предупреждения?

2023-12-14 19:59 UTC, vpyzhyanov commented on src/main/java/com/urfu/tgbot/services/StateService.java
> +    public State saveState(Long chatID, States state) {
Возвращаемое значение нигде не используется. Разве вы не видите предупреждения?

2023-12-14 19:59 UTC, vpyzhyanov commented on src/main/java/com/urfu/tgbot/services/StateService.java
> +    public State updateState(Long chatID, States state) {
аналогично

2023-12-14 19:59 UTC, vpyzhyanov commented on src/main/java/com/urfu/tgbot/services/StateService.java
> +        statesRepository.deleteById(chatID);
О_о зачем? Вы не читаете JavaDoc методов, которые используете? Почитайте его для метода save

2023-12-14 19:59 UTC, vpyzhyanov commented on src/main/java/com/urfu/tgbot/enums/States.java
> +package com.urfu.tgbot.enums;
Некорректно использовать множественное число в классах и пакетах. Я в прошлый раз это говорил.

2023-12-14 19:59 UTC, vpyzhyanov commented on src/main/java/com/urfu/tgbot/services/StateService.java
> +    public States getState(Long chatID) {
Вот тут прекрасно видно насколько неуместно множественное число

2023-12-14 19:59 UTC, vpyzhyanov commented on src/main/java/com/urfu/tgbot/services/StateService.java
> +            return statesRepository.findById(chatID).get().getState();
Прощай производительность. Просто так вы выполняете 2 одинаковых запроса в базу. Давайте что-ли третий добавим за компанию.

2023-12-14 19:59 UTC, vpyzhyanov commented on src/main/java/com/urfu/tgbot/services/StateService.java
> +        return null;
Учитесь у метода `findById` работать с отсутствием значения через класс `Optional`. Тогда и метод будет намного проще. Рекомендую вам всеми силами избегать null, если не хотите разбираться потом с неожиданными NPE.

2023-12-14 19:59 UTC, vpyzhyanov commented on src/main/java/com/urfu/tgbot/services/UserService.java
> +        if (userFromDb == null) {
Вы в блокноте код пишете? Или вы отключили все предупреждения? А зря, среда разработки подсвечивает вам очень глупую ошибку. У вас исключение произойдёт в предыдущей строчке

2023-12-14 19:59 UTC, vpyzhyanov commented on src/main/java/com/urfu/tgbot/services/UserService.java
> +        return userRepository.findById(chatID).get();
Всем приготовиться к тому, что тут произойдёт исключение в самый неожиданный момент

2023-12-14 19:59 UTC, vpyzhyanov commented on src/test/java/com/urfu/tgbot/commands/EditCommandTest.java
> +    @BeforeEach
не надо это делать в **каждом** тесте. Определите сразу с полями.

2023-12-14 19:59 UTC, vpyzhyanov commented on src/test/java/com/urfu/tgbot/commands/EditCommandTest.java
> +        verify(stateService).updateState(chatID, States.WAITING_FOR_INPUT_EDIT_CONFIRMATION);
в тесте смысла ноль, тупо дублирует вызов метода.

2023-12-14 19:59 UTC, vpyzhyanov commented on src/test/java/com/urfu/tgbot/commands/EditCommandTest.java
> +                """ + user.getFormattedString() + """
грубая ошибка: используется основной код в тесте (хотя в данном случае не сильно грубая, но всё равно)

2023-12-14 19:59 UTC, vpyzhyanov commented on src/test/java/com/urfu/tgbot/commands/EditCommandTest.java
> +        String expectedResponse = "Введите новое ФИО";
Переменные надо определять как можно ближе к тому месту, где они используются. В данном случае смысле выделять переменную вообще нет, она используется один раз. Далее идут ровно такие-то случаи.

2023-12-14 19:59 UTC, vpyzhyanov commented on src/test/java/com/urfu/tgbot/commands/HelpCommandTest.java
> +        String expectedCommandList = "Список доступных команд:<\n/start - старт бота\n/edit - изменение профиля\n/help - список доступных команд";
а смысл всё это проверять?

2023-12-14 19:59 UTC, vpyzhyanov commented on src/test/java/com/urfu/tgbot/commands/InputHandlerTest.java
> +        assertThrows(IllegalArgumentException.class, () -> inputHandler.checkFullName("Иванов Иван"));
не проверяется сообщение в исключении. Во всё классе так.

2023-12-14 19:59 UTC, vpyzhyanov commented on src/main/java/com/urfu/tgbot/commands/CommandManager.java
> +        String answer = messageText;
нормальные боты попугаями не прикидываются

2023-12-14 19:59 UTC, vpyzhyanov commented on src/main/java/com/urfu/tgbot/commands/NameEditor.java
> +public class NameEditor {
этот класс вообще нигде не используется. Его надо безжалостно удалить.

2023-12-18 18:30 UTC, vpyzhyanov commented on src/main/java/com/urfu/tgbot/botLogic/TelegramBot.java
> +package com.urfu.tgbot.botLogic;
В этом пакете логика отсутствует, тут только бот. Не надо никого обманывать

2023-12-18 18:30 UTC, vpyzhyanov commented on src/main/java/com/urfu/tgbot/botLogic/TelegramBot.java
> + * Класс для реализации Telegram-бота
Не надо воды, все и так видят, что это класс и ежу понятно, что у него есть реализация какая-то

2023-12-18 18:30 UTC, vpyzhyanov commented on src/main/java/com/urfu/tgbot/services/TelegramBot.java
> +
плохо прочитали замечание и неправильно исправили

2023-12-18 18:51 UTC, vpyzhyanov commented on src/main/java/com/urfu/tgbot/botLogic/TelegramBot.java
> +                throw new RuntimeException(e);
вы правда хотите грохнуть приложение целиком, просто из-за того, что в одной маленькой команде упала ошибка? Не отказоустойчивое приложение у вас.

2023-12-18 18:51 UTC, vpyzhyanov commented on src/main/java/com/urfu/tgbot/repository/UserRepository.java
> +    User findByUsername(String username);
где JavaDoc? Очень плохо что вы не смотрите шире и не исправляете замечания полностью. Для этого класса уже было замечание про JavaDoc, но вы исправили только то место, на которое я указал. Плохо.

2023-12-18 18:51 UTC, vpyzhyanov commented on src/main/java/com/urfu/tgbot/services/StateService.java
> +        statesRepository.deleteById(chatID);
Не исправлено! И ответа нет!

2023-12-18 18:51 UTC, vpyzhyanov commented on src/main/java/com/urfu/tgbot/enums/States.java
> +package com.urfu.tgbot.enums;
Не исправлено!

2023-12-18 18:51 UTC, vpyzhyanov commented on src/main/java/com/urfu/tgbot/service/StateService.java
> +            stateRepository.save(newState);
дублирование кода

2023-12-18 18:51 UTC, vpyzhyanov commented on src/main/java/com/urfu/tgbot/services/StateService.java
> +        return null;
молчаливый игнор замечаний будет караться снижением баллов, даже для некритичных замечаний как это, просто потому, что это нарушение норм приличия и проявление неуважения

2023-12-18 18:51 UTC, vpyzhyanov commented on src/test/java/com/urfu/tgbot/commands/EditCommandTest.java
> +    @BeforeEach
по сути ничего не изменилось(

2023-12-18 18:51 UTC, vpyzhyanov commented on src/test/java/com/urfu/tgbot/command/EditCommandTest.java
> +        editCommand = new EditCommand(stateService, userService);
лишнее действие

2023-12-18 18:51 UTC, vpyzhyanov commented on src/test/java/com/urfu/tgbot/commands/EditCommandTest.java
> +        String expectedResponse = "Введите новое ФИО";
Не исправлено!

2023-12-18 18:53 UTC, vpyzhyanov commented on src/test/java/com/urfu/tgbot/command/InputHandlerTest.java
> +            inputHandler.checkFullName("Иванов Иван");
не надо по два раза вызывать один и тот же метод и делать одну и ту же проверку. Вообще-то метод `assertThrows` возвращает исключение. Его можно взять и достать из него сообщение

2023-12-18 18:53 UTC, vpyzhyanov commented on src/test/java/com/urfu/tgbot/commands/InputHandlerTest.java
> +        assertThrows(IllegalArgumentException.class, () -> inputHandler.checkFullName("Иванов Иван"));
Неправильно исправлено

2023-12-18 18:54 UTC, vpyzhyanov commented on src/main/java/com/urfu/tgbot/commands/CommandManager.java
> +        String answer = messageText;
Не исправлено!

2023-12-18 19:04 UTC, CVanta commented on .gitignore
Исправлено

2023-12-18 19:04 UTC, CVanta commented on pom.xml
> +    </properties>
исправлено

2023-12-18 19:04 UTC, CVanta commented on pom.xml
> +                    <target>19</target>
Исправлено

2023-12-18 19:04 UTC, CVanta commented on src/main/java/com/urfu/tgbot/configs/BotConfig.java
> +@Configuration
Исправлено

2023-12-18 19:04 UTC, CVanta commented on src/main/java/com/urfu/tgbot/configs/BotConfig.java
> +    public void setBotToken(String botToken) {
Исправлено

2023-12-18 19:05 UTC, CVanta commented on src/main/java/com/urfu/tgbot/configs/BotConfig.java
> +    public void setBotName(String botName) {
Исправлено

2023-12-18 19:05 UTC, CVanta commented on src/main/java/com/urfu/tgbot/configs/BotInitializer.java
> +            api.registerBot(bot);
Исправлено

2023-12-18 19:05 UTC, CVanta commented on src/main/java/com/urfu/tgbot/configs/BotInitializer.java
> +
Исправлено

2023-12-18 19:06 UTC, CVanta commented on src/main/java/com/urfu/tgbot/enums/States.java
> +public enum States {
Исправлено

2023-12-18 19:07 UTC, CVanta commented on src/main/java/com/urfu/tgbot/services/TelegramBot.java
> +package com.urfu.tgbot.services;
Исправлено

2023-12-18 19:07 UTC, CVanta commented on src/main/java/com/urfu/tgbot/services/TelegramBot.java
> +    public TelegramBot(BotConfig config, CommandManager commandManager) {
Исправлено

2023-12-18 19:09 UTC, CVanta commented on src/main/java/com/urfu/tgbot/commands/CommandManager.java
> +    public String readInput(String messageText, long chatId) {
Исправлено

2023-12-18 19:09 UTC, CVanta commented on src/main/java/com/urfu/tgbot/commands/CommandManager.java
> +@Controller
Исправлено

2023-12-18 19:09 UTC, CVanta commented on src/main/java/com/urfu/tgbot/commands/CommandManager.java
> +            case null -> {
Исправлено

2023-12-18 19:09 UTC, CVanta commented on pom.xml
> +                    <compilerArgs>--enable-preview</compilerArgs>
Исправлено

2023-12-18 19:09 UTC, CVanta commented on src/main/java/com/urfu/tgbot/commands/CommandManager.java
> +    public String readCommand(String command, long chatID) {
Исправлено

2023-12-18 19:09 UTC, CVanta commented on src/main/java/com/urfu/tgbot/commands/CommandManager.java
> +                return "Не удалось разпознать команду";
Исправлено

2023-12-18 19:10 UTC, CVanta commented on src/main/java/com/urfu/tgbot/commands/StartCommand.java
> +@Controller
Исправлено

2023-12-18 19:10 UTC, CVanta commented on src/main/java/com/urfu/tgbot/commands/EditCommand.java
> +    public void updateState(long chatID) {
Исправлено

2023-12-18 19:10 UTC, CVanta commented on src/main/java/com/urfu/tgbot/commands/NameEditor.java
> + * Этот класс реализует изменени профиля пользователя
Исправлено

2023-12-18 19:10 UTC, CVanta commented on src/main/java/com/urfu/tgbot/commands/NameEditor.java
> +@Controller
Исправлено

2023-12-18 19:11 UTC, CVanta commented on src/main/java/com/urfu/tgbot/commands/NameEditor.java
> +        } catch (Exception e) {
Исправлено

2023-12-18 19:12 UTC, CVanta commented on src/main/java/com/urfu/tgbot/models/User.java
> +     * @return Отформатированная строковая representation информации о пользователе.
Лень, но вроде это не ошибка

2023-12-18 19:12 UTC, CVanta commented on src/main/java/com/urfu/tgbot/models/User.java
> +    public long getPhoneNumber() {
Исправлено

2023-12-18 19:13 UTC, CVanta commented on src/main/java/com/urfu/tgbot/models/User.java
> +     * @return Полное имя пользователя.
Вроде это не ошибка

2023-12-18 19:13 UTC, CVanta commented on src/main/java/com/urfu/tgbot/models/User.java
> +    public static class Builder {
Исправлено

2023-12-18 19:13 UTC, CVanta commented on src/main/java/com/urfu/tgbot/repositories/StatesRepository.java
> +public interface StatesRepository extends CrudRepository<State, Long> {
Исправлено

2023-12-18 19:14 UTC, CVanta commented on src/main/java/com/urfu/tgbot/services/StateService.java
> +@Component
Исправлено

2023-12-18 19:14 UTC, CVanta commented on src/main/java/com/urfu/tgbot/services/StateService.java
> +import java.util.List;
Исправлено

2023-12-18 19:14 UTC, CVanta commented on src/main/java/com/urfu/tgbot/services/StateService.java
> +    public State saveState(Long chatID, States state) {
Исправлено

2023-12-18 19:14 UTC, CVanta commented on src/main/java/com/urfu/tgbot/services/StateService.java
> +    public State updateState(Long chatID, States state) {
Исправлено

2023-12-18 19:16 UTC, vpyzhyanov requested changes
1. При сборке запускаются не все тесты! Вы намешали Junit 4 и Junit 5, зачем-то, всё из-за этого. Выберите что-то одно.
2. Почему мне приходится второй раз писать одни и те же замечания?
3. Исправлены не все замечания
4. Вспомните что такое правила хорошего тона в пулл реквесте

![image](https://github.com/CVanta/Naumen-project/assets/71599019/89127706-b675-449a-a4d4-450ad1dac93c)

Пока вы заработали только 2 из 5 баллов. У вас есть выбор: либо вы исправляете замечания ещё раз, либо я могу поставить всё что есть сейчас и принять задачу.

2023-12-18 19:16 UTC, vpyzhyanov commented on src/test/java/com/urfu/tgbot/command/CommandManagerTest.java
> +        commandManager = new CommandManager(startCommand, helpCommand, stateService, nameEditor, editCommand);
лишняя команда

2023-12-18 19:16 UTC, vpyzhyanov commented on src/test/java/com/urfu/tgbot/command/CommandManagerTest.java
> +    public void testHandleInputUpdateStateStartCommandStateNull() {
где JavaDoc?

2023-12-18 19:16 UTC, vpyzhyanov commented on src/test/java/com/urfu/tgbot/command/CommandManagerTest.java
> +        assertEquals("Введите номер телефона", response);
бессмысленная проверка. Вы же сами только что написали этот текст и тут же его проверяете. Не надо так делать. Достаточно проверить, что вызывался нужный метод.

Во всех остальных тестах точно так же

2023-12-18 19:16 UTC, vpyzhyanov commented on src/test/java/com/urfu/tgbot/command/EditCommandTest.java
> +    @Before
В чём прикол понижать с Junit 5 на JUnit 4? Чтобы тесты не запускались?

2023-12-18 19:16 UTC, vpyzhyanov commented on src/test/java/com/urfu/tgbot/service/StateServiceTest.java
> +     * Тест для метода getState, который проверяет получение текущего состояния, когда состояния не существует.
Описание совпадает с другим тестом

2023-12-18 19:16 UTC, vpyzhyanov commented on src/test/java/com/urfu/tgbot/service/StateServiceTest.java
> +        long chatId = 1234567890;
вот вам не лень писать это каждый раз. Вынесите в константу наконец

2023-12-18 19:16 UTC, vpyzhyanov commented on src/test/java/com/urfu/tgbot/service/StateServiceTest.java
> +        assertNull(currentState);
не надо создавать переменные, когда в этом нет никакой необходимости, пишите всё тут

2023-12-18 19:16 UTC, vpyzhyanov commented on src/test/java/com/urfu/tgbot/service/UserServiceTest.java
> +        assertThrows(Exception.class, () -> userService.addUser(existingUser));
нет проверки текста исключения. Почему мне приходится второй раз писать одни и те же замечания?

2023-12-18 19:16 UTC, vpyzhyanov commented on src/test/java/com/urfu/tgbot/service/UserServiceTest.java
> +        User user = new User("username", 1234567890);
ну вынесите его в поле класса, не надо дублировать это миллион раз

2023-12-18 19:16 UTC, vpyzhyanov commented on src/test/java/com/urfu/tgbot/service/UserServiceTest.java
> +    void testAddUser_NewUser() {
где JavaDoc? Почему мне приходится второй раз писать одни и те же замечания?

2023-12-18 19:16 UTC, CVanta commented on src/main/java/com/urfu/tgbot/services/StateService.java
> +        statesRepository.deleteById(chatID);
Исправлено, метод save удален, теперь только исправленный update

2023-12-18 19:18 UTC, CVanta commented on src/main/java/com/urfu/tgbot/enums/States.java
> +package com.urfu.tgbot.enums;
Исправлено, пытались назвать файл enum, но это невозможно, назвали enumeration

2023-12-18 19:18 UTC, CVanta commented on src/main/java/com/urfu/tgbot/services/StateService.java
> +    public States getState(Long chatID) {
Исправлено

2023-12-18 19:19 UTC, CVanta commented on src/main/java/com/urfu/tgbot/services/StateService.java
> +            return statesRepository.findById(chatID).get().getState();
Исправлено

2023-12-18 19:20 UTC, CVanta commented on src/main/java/com/urfu/tgbot/services/StateService.java
> +        return null;
Исправлено, теперь с отсутствием значения работаем через Optional

2023-12-18 19:21 UTC, CVanta commented on src/main/java/com/urfu/tgbot/services/UserService.java
> +        if (userFromDb == null) {
Исправлено

2023-12-18 19:22 UTC, CVanta commented on src/main/java/com/urfu/tgbot/services/UserService.java
> +        return userRepository.findById(chatID).get();
Исправлено

2023-12-18 19:31 UTC, CVanta commented on src/main/java/com/urfu/tgbot/commands/CommandManager.java
> +        String answer = messageText;
исправлено

2023-12-18 19:33 UTC, CVanta commented on src/main/java/com/urfu/tgbot/commands/NameEditor.java
> +public class NameEditor {
NameEditor используется в CommandManager и отвечает за изменение профиля пользователя, мы могли бы убрать его и написать эти методы в CommandManager, но это будет перегрузка функционалом для 1 класса, поэтому мы сделали отдельный класс

2023-12-18 19:33 UTC, CVanta commented on src/main/java/com/urfu/tgbot/botLogic/TelegramBot.java
> +package com.urfu.tgbot.botLogic;
Исправлено

2023-12-18 19:38 UTC, CVanta commented on src/main/java/com/urfu/tgbot/botLogic/TelegramBot.java
> + * Класс для реализации Telegram-бота
исправлено

2023-12-18 19:39 UTC, CVanta commented on src/main/java/com/urfu/tgbot/botLogic/TelegramBot.java
> +                throw new RuntimeException(e);
исправлено

2023-12-18 19:41 UTC, CVanta commented on src/main/java/com/urfu/tgbot/repository/UserRepository.java
> +    User findByUsername(String username);
исправлено

2023-12-18 19:43 UTC, CVanta commented on src/main/java/com/urfu/tgbot/services/TelegramBot.java
> +
исправлено

2023-12-18 19:44 UTC, CVanta commented on src/main/java/com/urfu/tgbot/repositories/UserRepository.java
> +public interface UserRepository extends CrudRepository<User, Long> {
исправлено

2023-12-18 19:49 UTC, CVanta commented on src/main/java/com/urfu/tgbot/service/StateService.java
> +            stateRepository.save(newState);
Вроде здесь нет дублирования кода, мы сначала проверяем есть ли состояние в базе, если его нет, то добавляем, если оно уже есть, то меняем на необходимое

2023-12-19 15:02 UTC, kub0metr commented on src/test/java/com/urfu/tgbot/service/UserServiceTest.java
> +    void testAddUser_NewUser() {
Исправлено

2023-12-19 15:03 UTC, kub0metr commented on src/test/java/com/urfu/tgbot/service/UserServiceTest.java
> +        User user = new User("username", 1234567890);
Исправлено

2023-12-19 15:03 UTC, kub0metr commented on src/test/java/com/urfu/tgbot/service/UserServiceTest.java
> +        assertThrows(Exception.class, () -> userService.addUser(existingUser));
Исправлено

2023-12-19 15:03 UTC, kub0metr commented on src/test/java/com/urfu/tgbot/service/StateServiceTest.java
> +        assertNull(currentState);
исправлено

2023-12-19 15:03 UTC, kub0metr commented on src/test/java/com/urfu/tgbot/service/StateServiceTest.java
> +        long chatId = 1234567890;
исправлено

2023-12-19 15:07 UTC, kub0metr commented on src/test/java/com/urfu/tgbot/service/StateServiceTest.java
> +     * Тест для метода getState, который проверяет получение текущего состояния, когда состояния не существует.
исправлено

2023-12-19 15:18 UTC, kub0metr commented on src/test/java/com/urfu/tgbot/command/EditCommandTest.java
> +    @Before
исправлено

2023-12-19 17:23 UTC, kub0metr commented on src/test/java/com/urfu/tgbot/command/CommandManagerTest.java
> +        assertEquals("Введите номер телефона", response);
исправлено

2023-12-19 17:23 UTC, kub0metr commented on src/test/java/com/urfu/tgbot/command/CommandManagerTest.java
> +    public void testHandleInputUpdateStateStartCommandStateNull() {
исправлено

2023-12-19 17:31 UTC, kub0metr commented on src/test/java/com/urfu/tgbot/commands/EditCommandTest.java
> +        String expectedResponse = "Введите новое ФИО";
Исправлено

2023-12-19 17:46 UTC, kub0metr commented on src/test/java/com/urfu/tgbot/command/EditCommandTest.java
> +        editCommand = new EditCommand(stateService, userService);
Исправлено

2023-12-19 17:47 UTC, kub0metr commented on src/test/java/com/urfu/tgbot/command/InputHandlerTest.java
> +            inputHandler.checkFullName("Иванов Иван");
Исправлено

2023-12-19 17:47 UTC, kub0metr commented on src/test/java/com/urfu/tgbot/command/CommandManagerTest.java
> +        commandManager = new CommandManager(startCommand, helpCommand, stateService, nameEditor, editCommand);
Исправлено

2023-12-19 17:47 UTC, kub0metr commented on src/test/java/com/urfu/tgbot/commands/InputHandlerTest.java
> +        assertThrows(IllegalArgumentException.class, () -> inputHandler.checkFullName("Иванов Иван"));
Исправлено

2023-12-19 17:48 UTC, kub0metr commented on src/test/java/com/urfu/tgbot/commands/HelpCommandTest.java
> +        String expectedCommandList = "Список доступных команд:<\n/start - старт бота\n/edit - изменение профиля\n/help - список доступных команд";
Исправлено

2023-12-19 17:56 UTC, CVanta commented on src/test/java/com/urfu/tgbot/commands/EditCommandTest.java
> +                """ + user.getFormattedString() + """
исправлено

2023-12-19 17:57 UTC, CVanta commented on src/test/java/com/urfu/tgbot/commands/EditCommandTest.java
> +        verify(stateService).updateState(chatID, States.WAITING_FOR_INPUT_EDIT_CONFIRMATION);
исправлено

2023-12-19 17:57 UTC, CVanta commented on src/test/java/com/urfu/tgbot/commands/EditCommandTest.java
> +    @BeforeEach
исправлено

2023-12-20 19:24 UTC, vpyzhyanov requested changes
> При сборке запускаются не все тесты! Вы намешали Junit 4 и Junit 5, зачем-то, всё из-за этого. Выберите что-то одно.

я до сих пор не вижу изменений в pom файле. Вы до сих пор не убрали JUnit 4. Или вы хотите, чтобы ситуация с тестами повторилась?

Задача принята. Как исправите последние замечания, можете мёрджить.

За ООП ставлю 4 балла (снизил за неполное исправление замечаний и за то, что повторно приходится делать одни и те же замечания)

2023-12-20 19:24 UTC, vpyzhyanov commented on src/main/java/com/urfu/tgbot/repository/UserRepository.java
> +    User findByUsername(String username);
Этот метод не используется нигде

2023-12-20 19:24 UTC, vpyzhyanov commented on src/main/java/com/urfu/tgbot/service/StateService.java
> +            stateRepository.save(newState);
Ну как нет?! Дважды вызывается один и тот же метод с одним и тем же параметром. Его надо вынести за пределы условия (в обоих ветках одинаковое действие делается)

2023-12-20 19:24 UTC, vpyzhyanov commented on src/main/java/com/urfu/tgbot/service/StateService.java
> +            stateRepository.deleteById(chatID);
Уже второй раз пишу, что замечание не исправлено!!! Третьего не будет, будет сразу 0 за всю задачу!

Неуместный вызов удаления. Читайте JavaDoc для метода save. Сохранение - это не создание, это **сохранение**.

2023-12-20 19:24 UTC, vpyzhyanov commented on src/main/java/com/urfu/tgbot/services/StateService.java
> +        statesRepository.deleteById(chatID);
Не исправлено №2. Но похоже вы не поняли замечание. Ок напишу новое и подробное, раз вы не видите на какую строчку указывает замечание.

2023-12-20 19:24 UTC, vpyzhyanov commented on src/test/java/com/urfu/tgbot/command/EditCommandTest.java
> +    @Before
что-то я до сих пор не вижу изменений в pom файле. Вы до сих пор не убрали JUnit 4. Или вы хотите, чтобы ситуация с тестами повторилась?

2023-12-21 08:02 UTC, CVanta commented on src/main/java/com/urfu/tgbot/service/StateService.java
> +            stateRepository.deleteById(chatID);
исправлено

2023-12-21 08:04 UTC, merged

2023-12-21 20:10 UTC, CVanta commented on src/main/java/com/urfu/tgbot/service/StateService.java
> +            stateRepository.save(newState);
исправлено

2023-12-21 20:10 UTC, CVanta commented on src/main/java/com/urfu/tgbot/repository/UserRepository.java
> +    User findByUsername(String username);
исправлено

2023-12-21 20:11 UTC, CVanta commented on src/main/java/com/urfu/tgbot/services/StateService.java
> +        statesRepository.deleteById(chatID);
исправлено

2023-12-21 20:11 UTC, CVanta commented on src/test/java/com/urfu/tgbot/command/EditCommandTest.java
> +    @Before
исправлено